### ISSUE TITLE
How to make it work on koa2? Could you help me?

### ISSUE THREAD

**Issue by paivaric** [johnhof/swagger-injector#17]

**Comment by johnhof** [comment]
Sorry for the late response. I havent looked into koa2 support yet. I'll take a look when i get a chance. I imagine its a non-trivial change to make it work for the foreseeable future. I'll need to remove the generator based middleware for that case.

A temporary work around would be to nest it inside a koa2 middleware function and bind the context. Though i dont have a working example at the moment.

**Comment by johnhof** [comment]
for what it's worth, koa2 is supported in version 3.0 (dropped support for koa).
